name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  container-job:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/upload-artifact@v3
        with:
         name: artifact         
         path: path/to/artifact/
