name: Check Dependecies

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  container-job:
     runs-on: ubuntu-latest
     steps:
      - name: temporary
        run: mkdir artifact
      - uses: actions/upload-artifact@v3
        with:         
         name: assets.zip
         path: ./root/
