name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  container-job:
     runs-on: ubuntu-latest
     steps:
      - run: mkdir ../artifact
      - uses: actions/upload-artifact@v3
        with:         
         name: artifact.zip         
         path: ../artifact
