name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  container-job:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/upload-artifact@v3
        with:
         working-directory: ${{ home }}
         name: artifact.zip         
         path: ${HOME}
